# Generated by Django 2.1.3 on 2019-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190107_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='number_of_followers',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='instagram',
            name='number_of_following',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='instagram',
            name='number_of_post',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='twitter',
            name='number_of_followers',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='twitter',
            name='number_of_following',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='twitter',
            name='number_of_post',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
