# Generated by Django 2.1.3 on 2019-02-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190220_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='number_of_followers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='number_of_following',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='number_of_post',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='number_of_followers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='number_of_following',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='number_of_post',
            field=models.IntegerField(default=1),
        ),
    ]
