# Generated by Django 2.1.3 on 2019-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190228_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='bio',
            field=models.CharField(default=1, max_length=160),
        ),
        migrations.AddField(
            model_name='instagram',
            name='location',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='twitter',
            name='bio',
            field=models.CharField(default=1, max_length=160),
        ),
        migrations.AddField(
            model_name='twitter',
            name='location',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
