# Generated by Django 2.1.3 on 2019-02-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190228_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='bio',
            field=models.CharField(default='unknown', max_length=160),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='location',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='bio',
            field=models.CharField(default='unknown', max_length=160),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='location',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
