# Generated by Django 2.1.3 on 2019-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190228_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('bio', models.CharField(default='unknown', max_length=280)),
                ('twitter', models.BooleanField()),
                ('instagram', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
