# Generated by Django 2.1.3 on 2019-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_postsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOpperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('number_of_likes', models.IntegerField(default=1)),
                ('hashtags', models.TextField(default='unknown', max_length=280)),
                ('twitter', models.BooleanField()),
                ('instagram', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postsocial',
            name='bio',
        ),
        migrations.AddField(
            model_name='postsocial',
            name='text',
            field=models.TextField(default='unknown', max_length=280),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='bio',
            field=models.TextField(default='unknown', max_length=160),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='bio',
            field=models.TextField(default='unknown', max_length=160),
        ),
    ]
