# Generated by Django 2.1.3 on 2019-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190228_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='followOpperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('number_of_followers', models.IntegerField(default=1)),
                ('hashtags', models.TextField(default='unknown', max_length=280)),
                ('twitter', models.BooleanField()),
                ('instagram', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
