# Generated by Django 2.1.3 on 2019-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_followopperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='followopperation',
            name='viewPast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='likeopperation',
            name='viewPast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postsocial',
            name='viewPast',
            field=models.BooleanField(default=True),
        ),
    ]
